spring.application.name=Backend

# Conexión a Supabase (Pooler de la región South America)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.beoskikjffoqmcvkgeaz
spring.datasource.password=2phX9Yn@P_GNU+e
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true